-- Seed forum_posts table with 20 sample posts
-- Database: if0_39892362_wp429
-- Table: forum_posts
-- Authors: Users from wp5x_fc_subscribers table (50 virtual customers)
-- Execute this SQL in phpMyAdmin after creating the forum_posts table and inserting subscribers

-- Insert 20 sample forum posts with authors from wp5x_fc_subscribers
-- Each post is associated with a different subscriber from the 50 virtual customers
INSERT INTO forum_posts (user_id, author_name, title, body, created_at) VALUES
(1, 'Emma Thompson', 'Amazing pottery collection from local artisans!', 'I recently purchased a handcrafted ceramic bowl and I''m absolutely in love with it! The quality is exceptional and knowing it was made by a local artisan makes it even more special. The story behind each piece really adds value to the purchase. Highly recommend checking out the pottery section!', NOW() - INTERVAL 20 DAY),
(3, 'Sophie Chen', 'Suggestion: Add filter by artisan location', 'Would it be possible to add a filter that allows us to search for artisans by their location? I''d love to support local makers in my area and discover crafts from specific regions. This would make the browsing experience much better!', NOW() - INTERVAL 19 DAY),
(5, 'Li Mei', 'The storytelling feature is wonderful', 'I really appreciate how each product includes the artisan''s story and background. It makes shopping feel more personal and meaningful. Learning about the craft traditions and techniques used is fascinating. Keep up the great work!', NOW() - INTERVAL 18 DAY),
(7, 'Sarah Johnson', 'Shipping times could be improved', 'I love the platform, but I think shipping times could be faster. My last order took about 2 weeks to arrive. Perhaps you could work with artisans to provide estimated shipping times upfront? This would help set better expectations.', NOW() - INTERVAL 17 DAY),
(9, 'Yuki Tanaka', 'Request: More video content of artisans at work', 'The photos are great, but I''d love to see more video content showing artisans creating their pieces. Watching the process would be so inspiring and educational. Maybe short clips showing techniques like wheel throwing or weaving?', NOW() - INTERVAL 16 DAY),
(11, 'Thomas Anderson', 'Great experience with customer service', 'I had a question about a product and reached out to support. The response was quick and very helpful. The team really cares about connecting customers with the right crafts. Thank you for the excellent service!', NOW() - INTERVAL 15 DAY),
(13, 'Ahmed Hassan', 'Wishlist feature would be helpful', 'I often find multiple items I''d like to purchase but can''t buy them all at once. A wishlist feature would be really useful so I can save items for later. Is this something you''re planning to add?', NOW() - INTERVAL 14 DAY),
(15, 'Carlos Rodriguez', 'Love the paper art collection!', 'The paper art section has some beautiful pieces. I bought a handmade journal and the craftsmanship is incredible. The attention to detail is remarkable. More paper art options would be fantastic!', NOW() - INTERVAL 13 DAY),
(17, 'William Davis', 'Suggestion: Artisan spotlight section', 'It would be great to have a monthly or weekly spotlight on featured artisans. This could include interviews, behind-the-scenes content, and special collections. It would help us get to know the makers better!', NOW() - INTERVAL 12 DAY),
(19, 'Daniel Kim', 'Mobile app would be convenient', 'The website works well on mobile, but a dedicated app would be even better. Push notifications for new products from favorite artisans, easier browsing, and quick checkout would enhance the experience significantly.', NOW() - INTERVAL 11 DAY),
(21, 'Mohammed Ali', 'Product quality exceeds expectations', 'I''ve made several purchases now and every item has exceeded my expectations. The artisans clearly take pride in their work. The authenticity and quality you can''t find in mass-produced items. This platform is doing something special!', NOW() - INTERVAL 10 DAY),
(23, 'Alexander Petrov', 'Could use more textile options', 'I love the textile section, but I''d like to see more variety. Perhaps more woven items, embroidered pieces, or traditional fabric patterns? The current selection is good, but more options would be wonderful.', NOW() - INTERVAL 9 DAY),
(25, 'Ryan O''Connor', 'Gift wrapping option needed', 'Many of these items would make perfect gifts! It would be great to have a gift wrapping option at checkout. Even a simple option would be appreciated. This could be a nice additional service.', NOW() - INTERVAL 8 DAY),
(27, 'Benjamin Clark', 'The forum is a great addition', 'Having this community space to share experiences and feedback is wonderful. It creates a sense of community around supporting local artisans. I''m looking forward to more discussions here!', NOW() - INTERVAL 7 DAY),
(29, 'Noah Jackson', 'Pricing seems fair for handmade items', 'I appreciate that the pricing reflects the time and skill that goes into each piece. While some items might seem expensive compared to mass-produced goods, the quality and uniqueness justify the cost. Fair trade for fair craft!', NOW() - INTERVAL 6 DAY),
(31, 'Lucas Silva', 'Suggestion: Virtual artisan workshops', 'Would you consider offering virtual workshops where artisans teach their craft? This could be a great way to engage the community and provide additional income for makers. I''d definitely sign up for pottery or weaving classes!', NOW() - INTERVAL 5 DAY),
(33, 'Sebastian Muller', 'Search function works well', 'The search and filter options make it easy to find what I''m looking for. Being able to search by category, price range, and artisan is very helpful. The interface is intuitive and user-friendly.', NOW() - INTERVAL 4 DAY),
(35, 'Raj Kumar', 'Woodcraft section needs more variety', 'The woodcraft items are beautiful, but I''d love to see more diverse pieces. Perhaps kitchen utensils, decorative items, or small furniture? The current selection is nice but could be expanded.', NOW() - INTERVAL 3 DAY),
(37, 'Andre Santos', 'Excellent packaging and presentation', 'My orders always arrive beautifully packaged. The care taken in presentation shows respect for both the artisan''s work and the customer. It makes receiving the items feel like opening a special gift!', NOW() - INTERVAL 2 DAY),
(39, 'Kenji Nakamura', 'Overall, this is a fantastic platform!', 'I''ve been using Heritage Craft Marketplace for a few months now and I''m really impressed. The mission to support local artisans, the quality of products, and the overall experience is excellent. Keep up the great work! This platform is making a real difference for both artisans and customers.', NOW() - INTERVAL 1 DAY);
